# Generated by Django 5.0.6 on 2024-06-19 14:36

import django.db.models.deletion
import simpplr.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=simpplr.utils.getMovieImageName)),
                ('director', models.CharField(max_length=255)),
                ('release_year', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('language', models.ForeignKey(default='hi', on_delete=django.db.models.deletion.SET_DEFAULT, to='tasks.languagemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
