# Generated by Django 5.0.6 on 2024-06-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_moviemodel_delete_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviemodel',
            name='image',
        ),
    ]
