# Generated by Django 5.0.6 on 2024-06-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_moviemodel_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='language',
            field=models.ForeignKey(default='hi', on_delete=django.db.models.deletion.CASCADE, to='tasks.languagemodel'),
        ),
    ]
